const fs = require('fs');
const path = 'src/app/result/page.tsx';
let content = fs.readFileSync(path, 'utf-8');

const oldBlock = `          {/* Template + Highlight controls */}\r\n          <div className="w-full flex justify-end px-4 pt-4 pb-4">\r\n            <div className="flex bg-[#0f1117]/90 backdrop-blur-md rounded-xl shadow-lg border border-[#006859]/30 overflow-hidden">\r\n              <button onClick={() => setSelectedTemplate("templateLetter")} className={\`px-3 py-2 text-[11px] font-bold transition-colors \${selectedTemplate === "templateLetter" ? "bg-primary text-white" : "text-white/60 hover:bg-white/10"}\`}>T1</button>\r\n              <div className="w-[1px] bg-white/10"></div>\r\n              <button onClick={() => setSelectedTemplate("templateA4")} className={\`px-3 py-2 text-[11px] font-bold transition-colors \${selectedTemplate === "templateA4" ? "bg-primary text-white" : "text-white/60 hover:bg-white/10"}\`}>T2</button>\r\n            </div>\r\n          </div>`;

const newBlock = `          {/* Template + Highlight controls */}\r\n          <div className="w-full flex items-center justify-between px-4 pt-4 pb-4">\r\n            {/* Undo / Redo — visible only in edit mode */}\r\n            {editMode ? (\r\n              <div className="flex items-center gap-1">\r\n                <button\r\n                  type="button"\r\n                  onClick={handleUndo}\r\n                  disabled={!canUndo}\r\n                  title="Undo (Ctrl+Z)"\r\n                  className={\`flex items-center justify-center w-8 h-8 rounded-xl border transition-all duration-200 \${\r\n                    canUndo\r\n                      ? 'bg-[#0f1117]/90 text-white/70 border-[#006859]/30 hover:bg-white/10 hover:text-white active:scale-95'\r\n                      : 'bg-transparent text-white/20 border-white/5 cursor-not-allowed'\r\n                  }\`}\r\n                >\r\n                  <Undo2 className="w-3.5 h-3.5" />\r\n                </button>\r\n                <button\r\n                  type="button"\r\n                  onClick={handleRedo}\r\n                  disabled={!canRedo}\r\n                  title="Redo (Ctrl+Y)"\r\n                  className={\`flex items-center justify-center w-8 h-8 rounded-xl border transition-all duration-200 \${\r\n                    canRedo\r\n                      ? 'bg-[#0f1117]/90 text-white/70 border-[#006859]/30 hover:bg-white/10 hover:text-white active:scale-95'\r\n                      : 'bg-transparent text-white/20 border-white/5 cursor-not-allowed'\r\n                  }\`}\r\n                >\r\n                  <Redo2 className="w-3.5 h-3.5" />\r\n                </button>\r\n              </div>\r\n            ) : (\r\n              <div />\r\n            )}\r\n            {/* T1 / T2 template switcher */}\r\n            <div className="flex bg-[#0f1117]/90 backdrop-blur-md rounded-xl shadow-lg border border-[#006859]/30 overflow-hidden">\r\n              <button onClick={() => setSelectedTemplate("templateLetter")} className={\`px-3 py-2 text-[11px] font-bold transition-colors \${selectedTemplate === "templateLetter" ? "bg-primary text-white" : "text-white/60 hover:bg-white/10"}\`}>T1</button>\r\n              <div className="w-[1px] bg-white/10"></div>\r\n              <button onClick={() => setSelectedTemplate("templateA4")} className={\`px-3 py-2 text-[11px] font-bold transition-colors \${selectedTemplate === "templateA4" ? "bg-primary text-white" : "text-white/60 hover:bg-white/10"}\`}>T2</button>\r\n            </div>\r\n          </div>`;

if (!content.includes(oldBlock)) {
  console.error('Block not found!');
  // Try to debug by printing what's around the area
  const idx = content.indexOf('Template + Highlight');
  console.log('Context:', JSON.stringify(content.substring(idx, idx+300)));
  process.exit(1);
}

content = content.replace(oldBlock, newBlock);
fs.writeFileSync(path, content, 'utf-8');
console.log('Done! Undo/Redo added beside T1/T2 on mobile.');
